name: ghostty
type: build
section: x11
priority: optional
homepage: https://github.com/ghostty-org/ghostty
description: >
  Ghostty - fast, feature-rich, and cross-platform terminal emulator
  that uses platform-native UI and GPU acceleration.
runtime_depends:
  - libgtk-4-1
  - libadwaita-1-0
  - libgtk4-layer-shell0

distros:
  - debian13
  - ubuntu2404