
name: fzf
type: build
section: utils
priority: optional
homepage: https://junegunn.github.io/fzf/
description: >
  A general-purpose command-line fuzzy finder.
  Interactive filter for files, command history, processes, git commits
  and more.

conflicts:
  - fzf

replaces:
  - fzf

provides:
  - fzf

produces:
  - fzf

distros:
  - debian13
  - ubuntu2404
