name: wl-clip-persist
type: build
section: utils
priority: optional
homepage: https://github.com/Linus789/wl-clip-persist
description: >
  Keep Wayland clipboard even after programs close.
  Reads clipboard data into memory whenever you copy something
  and overwrites the clipboard with that data, so it persists
  even after the source application exits.

produces:
  - wl-clip-persist

distros:
  - debian13
  - ubuntu2404
  - ubuntu2604
