name: bitwarden
type: repackage
arch: amd64
section: utils
priority: optional
homepage: https://bitwarden.com
description: >
  Bitwarden desktop application — open-source password manager.

distros:
  - debian13
  - ubuntu2404
