name: omakasui-nvim
type: repackage
arch: all
section: editors
priority: optional
homepage: https://github.com/LazyVim/LazyVim
description: >
  Pre-built LazyVim configuration with cached plugins.

runtime_depends:
  - nvim
  - git
  - gum

produces:
  - omakasui-nvim
  - omakub-nvim
  - omadeb-nvim
  - omari-nvim

distros:
  - debian13
  - ubuntu2404