name: xwayland-satellite
type: build
section: x11
priority: optional
homepage: https://github.com/Supreeeme/xwayland-satellite
description: >
  xwayland-satellite grants rootless Xwayland integration to any Wayland
  compositor implementing xdg_wm_base and viewporter.
  Particularly useful for compositors that do not want to implement
  support for rootless Xwayland themselves.

runtime_depends:
  - xwayland
  - libxcb1
  - libxcb-cursor0
  - libsystemd0

produces:
  - xwayland-satellite

distros:
  - debian13
  - ubuntu2404
  - ubuntu2604
