type: passthrough
distros:
  - debian13
  - ubuntu2404
  - ubuntu2604
source:
  url_amd64: "https://github.com/localsend/localsend/releases/download/v@VERSION@/LocalSend-@VERSION@-linux-x86-64.deb"
  url_arm64: "https://github.com/localsend/localsend/releases/download/v@VERSION@/LocalSend-@VERSION@-linux-arm-64.deb"
