type: passthrough
produces:
  - dbeaver-ce
distros:
  - debian13
  - ubuntu2404
  - ubuntu2604
source:
  url_amd64: "https://github.com/dbeaver/dbeaver/releases/download/@VERSION@/dbeaver-ce-@VERSION@-linux-x86_64.deb"
  url_arm64: "https://github.com/dbeaver/dbeaver/releases/download/@VERSION@/dbeaver-ce-@VERSION@-linux-aarch64.deb"
