type: repackage
produces:
  - elephant
  - elephant-1password
  - elephant-bitwarden
  - elephant-bluetooth
  - elephant-bookmarks
  - elephant-calc
  - elephant-clipboard
  - elephant-desktopapplications
  - elephant-files
  - elephant-menus
  - elephant-niriactions
  - elephant-nirisessions
  - elephant-playerctl
  - elephant-providerlist
  - elephant-runner
  - elephant-snippets
  - elephant-symbols
  - elephant-todo
  - elephant-unicode
  - elephant-websearch
  - elephant-windows
  - elephant-wireplumber
distros:
  - debian13
  - ubuntu2404
  - ubuntu2604