name: omakasui-zellij
type: repackage
arch: all
section: utils
priority: optional
homepage: https://zellij.dev
description: >
  Zellij configuration for Omakasui.

runtime_depends:
  - zellij
  - gum

depends_on: []

produces:
  - omakasui-zellij
  - omakub-zellij
  - omadeb-zellij
  - omari-zellij

distros:
  - debian13
  - ubuntu2404