type: passthrough
arch: all
distros:
  - debian13
  - ubuntu2404
  - ubuntu2604
source:
  url: "https://github.com/Stunkymonkey/nautilus-open-any-terminal/releases/download/@VERSION@/nautilus-extension-any-terminal_@VERSION@-1_all.deb"
